version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: ${DOCKER_APP_PREFIX-nginx-mirror}/app:latest
    networks:
      - appnet
    volumes:
      - ./public:/var/www/html/public
      - ./etc/nginx:/etc/nginx
    ports:
      - ${DOCKER_APP_PORT-80}80:80
      - ${DOCKER_APP_PORT-80}81:81
      - ${DOCKER_APP_PORT-80}82:82
    working_dir: /var/www/html
networks:
  appnet:
    driver: bridge
